### ISSUE TITLE
Support skip reason in the status line

### ISSUE THREAD

**Issue by bluetech** [asottile/pygments-pytest#28]
pytest 6.2 now prints skip/xfail reasons in the status line, e.g.

```
test_verbose_skip_reason.py::test_1 SKIPPED (Just because)  [ 50%]
test_verbose_skip_reason.py::test_2 XFAIL (Reason here)     [100%]
```

pytest uses pygments-pytest in its own docs and has a couple examples using this, so would be good if pygments-pytest supported this.

(I intend to submit a patch for this when I get a chance unless someone beats me to it)

**Comment by bluetech** [comment]
I tried to fix this but all of the recursive regexes made my head spin, sorry :(

**Comment by asottile** [comment]
yeah pygments is supper fiddly :( and pytest's output keeps getting less and less predictable instead of moreso

**Comment by asottile** [comment]
I believe the thing to modify is `progress_line`: https://github.com/asottile/pygments-pytest/blob/4a218a8e21db1326177fd9f98a0d4cf0cf49e8ba/pygments_pytest.py#L93

**Comment by bluetech** [comment]
I think it rather wants `progress_line_w` but I haven't fully figured out how it works. I tried to pprint `tokens` in its final form but that didn't help much :)

**Comment by asottile** [comment]
`progress_line_w` is to do the (really annoying by the way) state change where a warned test causes the rest of the run to be colored yellow, or a failed test to cause the rest of the test to be colored red -- it shouldn't need modification to implement what you're looking for here
